cargo rustc --release -v -- "-Clink-args=-mwindows"
cd "target/release"
del /Q "pbook-gui.zip"
mkdir "pbook-gui"
copy "pbook-gui.exe" "pbook-gui\pbook-gui.exe"
copy "pbook-gui.exe.manifest" "pbook-gui\pbook-gui.exe.manifest"
copy "iup.dll" "pbook-gui\iup.dll"
"..\..\windows-deps\7z\7za.exe" a "pbook-gui.zip" "pbook-gui"
rd /S /Q "pbook-gui"
cd "..\.."